CREATE TABLE IF NOT EXISTS raw_data.increment_states
(
    incr_pack_run_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    package_smd varchar(50),
    subscr_id varchar(50),
    obj_type varchar(20),
    objs_in_pack integer,
    workflow_end_dt timestamp,
    start_dt timestamp,
    end_dt timestamp,
    target_table varchar(50),
    min_ctl_loading bigint,
    max_ctl_loading bigint,
    incrementation_state integer
);
-- Добавить кому-то права на чтение/изменение?

CREATE SCHEMA IF NOT EXISTS raw_data_increment;

CREATE TABLE IF NOT EXISTS raw_data_increment.espd_mat
(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    package_smd varchar(50),
    subscr_id varchar(50),
    package_smd_dt timestamp(6),
    workflow_run_id bigint,
    workflow_name varchar(128),
    workflow_status varchar(4000),
    workflow_start_dt timestamp(6),
    workflow_end_dt timestamp(6),
    espd_status varchar(20),
    espd_err_text text,
    is_partitioned integer,
    objs integer,
    objs_err integer
);

CREATE TABLE IF NOT EXISTS raw_data_increment.espd_mat_obj
(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    package_smd varchar(50),
    mater_id varchar(50),
    status_smd varchar(50),
    obj_id integer,
    mater_tgt_state varchar(50),
    mater_tgt_date timestamp(6),
    workflow_run_id bigint,
    src_creationdt timestamp(6),
    src_expirationdt timestamp(6),
    src_plannedstartdt timestamp(6),
    src_real_scheme varchar(200),
    src_real_table varchar(200),
    mater_tgt_last_error varchar(4000),
    subscr_id varchar(50),
    to_ignore integer
);

