DROP TABLE IF EXISTS TT_DROP;
CREATE TEMPORARY TABLE TT_DROP AS
SELECT CALLID, SEGMENT, SEGSTOP, CTL_VALIDFROM, CTLLOADING, MAX(CTL_VALIDFROM) OVER(PARTITION BY CALLID, SEGMENT, SEGSTOP) AS MAXCTL, MAX(CTLLOADING) OVER(PARTITION BY CALLID, SEGMENT, SEGSTOP) AS MAXCTLLOADING
FROM RAW_DATA.ECHI;
DELETE FROM TT_DROP
WHERE CTL_VALIDFROM = MAXCTL AND CTLLOADING = MAXCTLLOADING;
-- НАЙДЕНО ДУБЛИКАТОВ
SELECT SUM(CNT) FROM (
                         SELECT COUNT(*) - 1 AS CNT
                         FROM RAW_DATA.ECHI
                         GROUP BY CALLID, SEGMENT, SEGSTOP
                         HAVING COUNT(*) > 1
                     ) AS C;
-- УДАЛЯТСЯ СКРИПТОМ
SELECT COUNT(*) FROM RAW_DATA.ECHI
WHERE CONCAT(CAST(CALLID AS VARCHAR), CAST(SEGMENT AS VARCHAR), CAST(SEGSTOP AS VARCHAR), CAST(CTL_VALIDFROM AS VARCHAR), CAST(CTLLOADING AS VARCHAR)) IN (SELECT CONCAT(CAST(CALLID AS VARCHAR), CAST(SEGMENT AS VARCHAR), CAST(SEGSTOP AS VARCHAR), CAST(CTL_VALIDFROM AS VARCHAR), CAST(CTLLOADING AS VARCHAR)) FROM TT_DROP);
-- ЕСЛИ ЗНАЧЕНИЯ РАВНЫ, МОЖНО БЕЗОПАСНО УДАЛЯТЬ
DELETE FROM RAW_DATA.ECHI
WHERE CONCAT(CAST(CALLID AS VARCHAR), CAST(SEGMENT AS VARCHAR), CAST(SEGSTOP AS VARCHAR), CAST(CTL_VALIDFROM AS VARCHAR), CAST(CTLLOADING AS VARCHAR)) IN (SELECT CONCAT(CAST(CALLID AS VARCHAR), CAST(SEGMENT AS VARCHAR), CAST(SEGSTOP AS VARCHAR), CAST(CTL_VALIDFROM AS VARCHAR), CAST(CTLLOADING AS VARCHAR)) FROM TT_DROP);
DROP TABLE IF EXISTS TT_DROP;
SELECT CASE WHEN SUM(CNT) IS NULL THEN 'Поздравляем!' ELSE 'Что то пошло не так!' END FROM (
                         SELECT COUNT(*) - 1 AS CNT
                         FROM RAW_DATA.ECHI
                         GROUP BY CALLID, SEGMENT, SEGSTOP
                         HAVING COUNT(*) > 1
                     ) AS C;